#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Linux kernel symbol namespace import generator
#
# This script requires at least spatch
# version 1.0.6.
SPATCH_REQ_VERSION="1.0.6"

DIR="$(dirname $(readlink -f $0))/.."
SPATCH="`which ${SPATCH:=spatch}`"
if [ ! -x "$SPATCH" ]; then
    echo 'spatch is part of the Coccinelle project and is available at http://coccinelle.lip6.fr/'
    exit 1
fi

SPATCH_REQ_VERSION_NUM=$(echo $SPATCH_REQ_VERSION | ${DIR}/scripts/ld-version.sh)
SPATCH_VERSION=$($SPATCH --version | head -1 | awk '{print $3}')
SPATCH_VERSION_NUM=$(echo $SPATCH_VERSION | ${DIR}/scripts/ld-version.sh)

if [ "$SPATCH_VERSION_NUM" -lt "$SPATCH_REQ_VERSION_NUM" ] ; then
    echo 'spatch needs to be version 1.06 or higher'
    exit 1
fi

generate_deps_for_ns() {
    $SPATCH --very-quiet --in-place --sp-file $srctree/scripts/add_namespace.cocci -D ns=$1 $2
}

generate_deps() {
    local mod_file=`echo $@ | sed -e 's/\.ns_deps/\.mod/'`
    local mod_name=`cat $mod_file | sed -n 1p | sed -e 's/\/[^.]*$//'`
    local mod_source_files=`cat $mod_file | sed -n 2p | sed -e 's/\.o/\.c/'`
    for ns in `cat $@`; do
	echo "Adding namespace $ns to module $mod_name (if needed)."
        generate_deps_for_ns $ns $mod_source_files
    done
}

for f in `find $srctree/.tmp_versions/ -name *.ns_deps`; do
    generate_deps $f
done
